apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scheduler
  name: scheduler
spec:
  selector:
    matchLabels:
      app: scheduler
  replicas: 1
  template:
    metadata:
      labels:
        app: scheduler
      name: scheduler
    spec:
      containers:
        - name: scheduler
          image: kelseyhightower/scheduler:0.4.0
        - name: kubectl
          image: kelseyhightower/kubectl:1.3.4
          args:
            - "proxy"
